// This should match Application.Library.Settings.EndpointCatalog
export const ENDPOINT_CATALOG = {
  Books: [
    'Library.Books.Create',
    'Library.Books.Delete',
    'Library.Books.GetAll',
    'Library.Books.GetAllEntities',
    'Library.Books.GetById',
    'Library.Books.GetCount',
    'Library.Books.GetCountByLanguage',
    'Library.Books.GetCountByPublisher',
    'Library.Books.GetCountByPublishPlace',
    'Library.Books.GetCountBySubject',
    'Library.Books.GetCountByYear',
    'Library.Books.GetList',
    'Library.Books.GetStatistics',
    'Library.Books.GetVolumeCount',
    'Library.Books.Search',
    'Library.Books.Update',
  ],
  Cities: [
    'Library.Cities.Create',
    'Library.Cities.Delete',
    'Library.Cities.GetAll',
    'Library.Cities.GetById',
    'Library.Cities.GetList',
    'Library.Cities.GetNames',
    'Library.Cities.Update',
  ],
  Gaps: [
    'Library.Gaps.Create',
    'Library.Gaps.Delete',
    'Library.Gaps.GetAll',
    'Library.Gaps.GetById',
    'Library.Gaps.GetList',
    'Library.Gaps.GetNames',
    'Library.Gaps.Update',
  ],
  Languages: [
    'Library.Languages.Create',
    'Library.Languages.Delete',
    'Library.Languages.GetAll',
    'Library.Languages.GetById',
    'Library.Languages.GetList',
    'Library.Languages.GetNames',
    'Library.Languages.Update',
  ],
  Manuscripts: [
    'Library.Manuscripts.Create',
    'Library.Manuscripts.Delete',
    'Library.Manuscripts.GetAll',
    'Library.Manuscripts.GetAllEntities',
    'Library.Manuscripts.GetById',
    'Library.Manuscripts.GetCount',
    'Library.Manuscripts.GetCountByGap',
    'Library.Manuscripts.GetCountByLanguage',
    'Library.Manuscripts.GetCountBySubject',
    'Library.Manuscripts.GetCountByWritingPlace',
    'Library.Manuscripts.GetCountByYear',
    'Library.Manuscripts.GetList',
    'Library.Manuscripts.GetStatistics',
    'Library.Manuscripts.Search',
    'Library.Manuscripts.Update',
  ],
  Publications: [
    'Library.Publications.Create',
    'Library.Publications.Delete',
    'Library.Publications.GetAll',
    'Library.Publications.GetAllEntities',
    'Library.Publications.GetById',
    'Library.Publications.GetCount',
    'Library.Publications.GetCountByLanguage',
    'Library.Publications.GetCountByPublishDate',
    'Library.Publications.GetCountByPublishPlace',
    'Library.Publications.GetCountBySubject',
    'Library.Publications.GetCountByType',
    'Library.Publications.GetList',
    'Library.Publications.GetStatistics',
    'Library.Publications.Search',
    'Library.Publications.Update',
  ],
  PublicationTypes: [
    'Library.PublicationTypes.Create',
    'Library.PublicationTypes.Delete',
    'Library.PublicationTypes.GetAll',
    'Library.PublicationTypes.GetById',
    'Library.PublicationTypes.GetList',
    'Library.PublicationTypes.GetNames',
    'Library.PublicationTypes.Update',
  ],
  Publishers: [
    'Library.Publishers.Create',
    'Library.Publishers.Delete',
    'Library.Publishers.GetAll',
    'Library.Publishers.GetById',
    'Library.Publishers.GetList',
    'Library.Publishers.GetNames',
    'Library.Publishers.Update',
  ],
  Settings: [
    'Library.Settings.AssignRoleToUser',
    'Library.Settings.CreateRole',
    'Library.Settings.GetAll',
    'Library.Settings.GetAllEntities',
    'Library.Settings.GetAllRoles',
    'Library.Settings.GetBackground',
    'Library.Settings.GetById',
    'Library.Settings.GetByName',
    'Library.Settings.GetMainTitle',
    'Library.Settings.GetUserRoles',
    'Library.Settings.RemoveRoleFromUser',
    'Library.Settings.Update',
    'Library.Settings.UpdateRoleEndpoints',
  ],
  Subjects: [
    'Library.Subjects.Create',
    'Library.Subjects.Delete',
    'Library.Subjects.GetAll',
    'Library.Subjects.GetById',
    'Library.Subjects.GetList',
    'Library.Subjects.GetNames',
    'Library.Subjects.Update',
  ],
  Users: [
    'Library.Users.Create',
    'Library.Users.Delete',
    'Library.Users.GetAll',
    'Library.Users.GetAllEntities',
    'Library.Users.GetByUserName',
    'Library.Users.GetFullName',
    'Library.Users.GetList',
    'Library.Users.Revoke',
    'Library.Users.Update',
  ],
  Attachments: [
    'Library.Attachments.Upload',
    'Library.Attachments.Delete',
    'Library.Attachments.GetByEntity',
  ],
};

